Update packaging steps

diff --git a/.github/workflows/cvp-extension-builder.yml b/.github/workflows/cvp-extension-builder.yml
--- a/.github/workflows/cvp-extension-builder.yml
+++ b/.github/workflows/cvp-extension-builder.yml
@@ -140,36 +140,37 @@ jobs:
           tar czvf ${env.distro_dir}.tgz ${env.distro_dir}
 
       - name: Save the tarball to the RPM branch
-        git status || true
-        git config --local user.name actions-user
-        git config --local user.email "actions@github.com"
-        #
-        # List the files in the repo
-        #
-        ls -la
-        #
-        # Show the current repo status
-        #
-        git status
-        #
-        # Remove all the files in the repo except the .git folder,
-        # the README file, and the coverage file. 'or' the command
-        # to true since it will fail when trying to delete '.' and '..'
-        #
-        shopt -s dotglob extglob
-        rm -rf !(.git|${env.distro_dir}.tgz) || true
-        #
-        if [ $(git ls-files --others | grep ${env.distro_dir}.tgz ) ] ; then
-          echo "Uploading new RPM package"
-          # XXX
-          # # Copy the version of README from the coverage-badge branch
-          # curl https://raw.githubusercontent.com/aristanetworks/vane/coverage-badge/README.md -o README.md
-          # Add and commit all the changes we just made, so we end up committing
-          # just the README and the coverage badge to the coverage-badge branch
-          git add --all
+        run: |
+          git status || true
+          git config --local user.name actions-user
+          git config --local user.email "actions@github.com"
+          #
+          # List the files in the repo
+          #
+          ls -la
+          #
+          # Show the current repo status
+          #
           git status
-          # Make the commit, but it will not be saved in GitHub on the working branch
-          git commit -am "Uploading new RPM package"
-          # Push the commit to the rpm-packages branch (not to the working branch or develop)
-          git push -f origin ${{ github.ref }}:gar-rpm-packages
-        fi
+          #
+          # Remove all the files in the repo except the .git folder,
+          # the README file, and the coverage file. 'or' the command
+          # to true since it will fail when trying to delete '.' and '..'
+          #
+          shopt -s dotglob extglob
+          rm -rf !(.git|${env.distro_dir}.tgz) || true
+          #
+          if [ $(git ls-files --others | grep ${env.distro_dir}.tgz ) ] ; then
+            echo "Uploading new RPM package"
+            # XXX
+            # # Copy the version of README from the coverage-badge branch
+            # curl https://raw.githubusercontent.com/aristanetworks/vane/coverage-badge/README.md -o README.md
+            # Add and commit all the changes we just made, so we end up committing
+            # just the README and the coverage badge to the coverage-badge branch
+            git add --all
+            git status
+            # Make the commit, but it will not be saved in GitHub on the working branch
+            git commit -am "Uploading new RPM package"
+            # Push the commit to the rpm-packages branch (not to the working branch or develop)
+            git push -f origin ${{ github.ref }}:gar-rpm-packages
+          fi
