Work on pip install pipeline job

diff --git a/.github/workflows/development-ci.yml b/.github/workflows/development-ci.yml
--- a/.github/workflows/development-ci.yml
+++ b/.github/workflows/development-ci.yml
@@ -105,6 +105,47 @@ jobs:
           eval "${{ env.poetry_home }}"
           pylint ${{ env.python }}
 
+  pip-install:
+    # Validate that the pip installation of Vane works properly
+
+    runs-on: ubuntu-latest
+
+    steps:
+
+      - name: Check out the repository
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Install Python 3.9
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.9'
+          # architecture: 'x64' # The default
+
+      - name: Display the Python version
+        run: python -c "import sys; print(sys.version)"
+
+      - name: Install Vane and dependencies
+        # Install Vane using pip
+        run: |
+          python -m pip install --upgrade pip
+          pip install .
+
+      - name: Check the vane name reported with python setup.py
+        run: |
+          vane_name=$(python setup.py --name)
+          if [[ ! "vane" =~ "$vane_name" ]]; then
+            echo "::error Invalid name reported for Vane application: $vane_name"
+            exit 1
+          fi
+
+      # - name: Run some basic checks after installation and put the results in the environment for testing
+      #   run: |
+      #     echo "vane_name=$(python setup.py --name 2>&1)" >> $GITHUB_ENV
+      #     echo "vane_version=$(python setup.py --version 2>&1)" >> $GITHUB_ENV
+      #     echo "vane_help=$(vane --help 2>&1)" >> $GITHUB_ENV
+
   unittest:
     # Run the Vane unittests
     #   If the tests pass, coverage will be calculated and reported to the output to be used
